[I 00:35:04.450 LabApp] The port 8888 is already in use, trying another port.
[I 00:35:05.804 LabApp] JupyterLab extension loaded from /software/astro/anaconda/anaconda3-2019.10/lib/python3.7/site-packages/jupyterlab
[I 00:35:05.804 LabApp] JupyterLab application directory is /software/astro/anaconda/anaconda3-2019.10/share/jupyter/lab
[I 00:35:11.990 LabApp] Serving notebooks from local directory: /lustre/hpc/astro/bmce/Dusty_Tails/opacs_jankovic/calc_dust_opac
[I 00:35:11.990 LabApp] Jupyter Notebook 6.1.6 is running at:
[I 00:35:11.990 LabApp] http://localhost:8889/?token=43b22270af6c3e8073f999098a4645493785a209f9cacbbb
[I 00:35:11.990 LabApp]  or http://127.0.0.1:8889/?token=43b22270af6c3e8073f999098a4645493785a209f9cacbbb
[I 00:35:11.991 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 00:35:12.140 LabApp] 
    
    To access the notebook, open this file in a browser:
        file:///lustre/hpc/astro/bmce/.local/share/jupyter/runtime/nbserver-95886-open.html
    Or copy and paste one of these URLs:
        http://localhost:8889/?token=43b22270af6c3e8073f999098a4645493785a209f9cacbbb
     or http://127.0.0.1:8889/?token=43b22270af6c3e8073f999098a4645493785a209f9cacbbb
[I 00:37:53.405 LabApp] 302 GET /?token=43b22270af6c3e8073f999098a4645493785a209f9cacbbb (::1) 1.200000ms
[W 00:38:09.362 LabApp] The extension "@ijmbarr/jupyterlab_spellchecker" is outdated.
    
[W 00:38:09.364 LabApp] The extension "@jupyterlab/latex" is outdated.
    
[W 00:38:09.365 LabApp] The extension "@aquirdturtle/collapsible_headings" is outdated.
    
[W 00:38:09.368 LabApp] The extension "@jupyterlab/toc" is outdated.
    
[W 00:38:09.370 LabApp] The extension "@jupyter-widgets/jupyterlab-manager" is outdated.
    
[E 00:38:16.195 LabApp] Uncaught exception GET /api/nbconvert?1656887887564 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8889', method='GET', uri='/api/nbconvert?1656887887564', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/software/astro/anaconda/anaconda3-2019.10/lib/python3.7/site-packages/tornado/web.py", line 1702, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/software/astro/anaconda/anaconda3-2019.10/lib/python3.7/site-packages/tornado/web.py", line 3173, in wrapper
        return method(self, *args, **kwargs)
      File "/software/astro/anaconda/anaconda3-2019.10/lib/python3.7/site-packages/notebook/services/nbconvert/handlers.py", line 18, in get
        exporters = base.get_export_names()
      File "/software/astro/anaconda/anaconda3-2019.10/lib/python3.7/site-packages/nbconvert/exporters/base.py", line 141, in get_export_names
        e = get_exporter(exporter_name)(config=config)
      File "/software/astro/anaconda/anaconda3-2019.10/lib/python3.7/site-packages/nbconvert/exporters/base.py", line 102, in get_exporter
        if getattr(exporter(config=config), 'enabled', True):
      File "/software/astro/anaconda/anaconda3-2019.10/lib/python3.7/site-packages/nbconvert/exporters/templateexporter.py", line 325, in __init__
        super().__init__(config=config, **kw)
      File "/software/astro/anaconda/anaconda3-2019.10/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 114, in __init__
        self._init_preprocessors()
      File "/software/astro/anaconda/anaconda3-2019.10/lib/python3.7/site-packages/nbconvert/exporters/templateexporter.py", line 491, in _init_preprocessors
        conf = self._get_conf()
      File "/software/astro/anaconda/anaconda3-2019.10/lib/python3.7/site-packages/nbconvert/exporters/templateexporter.py", line 509, in _get_conf
        if conf_path.exists():
      File "/software/astro/anaconda/anaconda3-2019.10/lib/python3.7/pathlib.py", line 1361, in exists
        self.stat()
      File "/software/astro/anaconda/anaconda3-2019.10/lib/python3.7/pathlib.py", line 1183, in stat
        return self._accessor.stat(self)
    PermissionError: [Errno 13] Permission denied: '/software/astro/anaconda/anaconda3-2019.10/share/jupyter/nbconvert/templates/html/conf.json'
[W 00:38:16.344 LabApp] Unhandled error
[E 00:38:16.345 LabApp] {
      "Host": "localhost:8889",
      "Connection": "keep-alive",
      "Sec-Ch-Ua": "\".Not/A)Brand\";v=\"99\", \"Google Chrome\";v=\"103\", \"Chromium\";v=\"103\"",
      "Dnt": "1",
      "Sec-Ch-Ua-Mobile": "?0",
      "Authorization": "token 43b22270af6c3e8073f999098a4645493785a209f9cacbbb",
      "Content-Type": "application/json",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36",
      "X-Xsrftoken": "2|28a038a3|13e80ed357817dfc404a5ca12ae33a3b|1656887873",
      "Sec-Ch-Ua-Platform": "\"macOS\"",
      "Accept": "*/*",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Sec-Fetch-Dest": "empty",
      "Referer": "http://localhost:8889/lab",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-DK,en-US;q=0.9,en-GB;q=0.8,en;q=0.7,pt-PT;q=0.6,pt;q=0.5,da-DK;q=0.4,da;q=0.3",
      "Cookie": "_xsrf=2|28a038a3|13e80ed357817dfc404a5ca12ae33a3b|1656887873; username-localhost-8889=\"2|1:0|10:1656887885|23:username-localhost-8889|44:YWJkNzBjMmU2OWY0NGMyY2IzMjNlODA5YWMwZWMxM2M=|0885c19e78123667989575757576394c463941e3ce62e342a3400e6820635496\""
    }
[E 00:38:16.346 LabApp] 500 GET /api/nbconvert?1656887887564 (::1) 8335.460000ms referer=http://localhost:8889/lab
[E 00:38:16.504 LabApp] Uncaught exception GET /api/nbconvert?1656887887539 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8889', method='GET', uri='/api/nbconvert?1656887887539', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/software/astro/anaconda/anaconda3-2019.10/lib/python3.7/site-packages/tornado/web.py", line 1702, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/software/astro/anaconda/anaconda3-2019.10/lib/python3.7/site-packages/tornado/web.py", line 3173, in wrapper
        return method(self, *args, **kwargs)
      File "/software/astro/anaconda/anaconda3-2019.10/lib/python3.7/site-packages/notebook/services/nbconvert/handlers.py", line 18, in get
        exporters = base.get_export_names()
      File "/software/astro/anaconda/anaconda3-2019.10/lib/python3.7/site-packages/nbconvert/exporters/base.py", line 141, in get_export_names
        e = get_exporter(exporter_name)(config=config)
      File "/software/astro/anaconda/anaconda3-2019.10/lib/python3.7/site-packages/nbconvert/exporters/base.py", line 102, in get_exporter
        if getattr(exporter(config=config), 'enabled', True):
      File "/software/astro/anaconda/anaconda3-2019.10/lib/python3.7/site-packages/nbconvert/exporters/templateexporter.py", line 325, in __init__
        super().__init__(config=config, **kw)
      File "/software/astro/anaconda/anaconda3-2019.10/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 114, in __init__
        self._init_preprocessors()
      File "/software/astro/anaconda/anaconda3-2019.10/lib/python3.7/site-packages/nbconvert/exporters/templateexporter.py", line 491, in _init_preprocessors
        conf = self._get_conf()
      File "/software/astro/anaconda/anaconda3-2019.10/lib/python3.7/site-packages/nbconvert/exporters/templateexporter.py", line 509, in _get_conf
        if conf_path.exists():
      File "/software/astro/anaconda/anaconda3-2019.10/lib/python3.7/pathlib.py", line 1361, in exists
        self.stat()
      File "/software/astro/anaconda/anaconda3-2019.10/lib/python3.7/pathlib.py", line 1183, in stat
        return self._accessor.stat(self)
    PermissionError: [Errno 13] Permission denied: '/software/astro/anaconda/anaconda3-2019.10/share/jupyter/nbconvert/templates/html/conf.json'
[W 00:38:16.505 LabApp] Unhandled error
[E 00:38:16.505 LabApp] {
      "Host": "localhost:8889",
      "Connection": "keep-alive",
      "Sec-Ch-Ua": "\".Not/A)Brand\";v=\"99\", \"Google Chrome\";v=\"103\", \"Chromium\";v=\"103\"",
      "Dnt": "1",
      "Sec-Ch-Ua-Mobile": "?0",
      "Authorization": "token 43b22270af6c3e8073f999098a4645493785a209f9cacbbb",
      "Content-Type": "application/json",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36",
      "X-Xsrftoken": "2|28a038a3|13e80ed357817dfc404a5ca12ae33a3b|1656887873",
      "Sec-Ch-Ua-Platform": "\"macOS\"",
      "Accept": "*/*",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Sec-Fetch-Dest": "empty",
      "Referer": "http://localhost:8889/lab",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-DK,en-US;q=0.9,en-GB;q=0.8,en;q=0.7,pt-PT;q=0.6,pt;q=0.5,da-DK;q=0.4,da;q=0.3",
      "Cookie": "_xsrf=2|28a038a3|13e80ed357817dfc404a5ca12ae33a3b|1656887873; username-localhost-8889=\"2|1:0|10:1656887885|23:username-localhost-8889|44:YWJkNzBjMmU2OWY0NGMyY2IzMjNlODA5YWMwZWMxM2M=|0885c19e78123667989575757576394c463941e3ce62e342a3400e6820635496\""
    }
[E 00:38:16.506 LabApp] 500 GET /api/nbconvert?1656887887539 (::1) 159.220000ms referer=http://localhost:8889/lab
[I 00:38:16.506 LabApp] Build is up to date
[W 00:38:19.411 LabApp] 404 GET /api/contents/opacs_jankovic/calc_dust_opac/calc_planck_opac.ipynb?content=0&1656887896665 (::1): No such file or directory: opacs_jankovic/calc_dust_opac/calc_planck_opac.ipynb
[W 00:38:19.411 LabApp] No such file or directory: opacs_jankovic/calc_dust_opac/calc_planck_opac.ipynb
[W 00:38:19.412 LabApp] 404 GET /api/contents/opacs_jankovic/calc_dust_opac/calc_planck_opac.ipynb?content=0&1656887896665 (::1) 2.120000ms referer=http://localhost:8889/lab
[W 00:38:19.550 LabApp] 404 GET /api/contents/opacs_jankovic/calc_dust_opac/corundum_K95?1656887899265 (::1): No such file or directory: opacs_jankovic/calc_dust_opac/corundum_K95
[W 00:38:19.550 LabApp] No such file or directory: opacs_jankovic/calc_dust_opac/corundum_K95
[W 00:38:19.551 LabApp] 404 GET /api/contents/opacs_jankovic/calc_dust_opac/corundum_K95?1656887899265 (::1) 1.040000ms referer=http://localhost:8889/lab
[W 00:38:31.420 LabApp] Notebook format_opt_const.ipynb is not trusted
[I 00:38:33.115 LabApp] Kernel started: e16d7323-78e0-482f-b65a-81c6d2ed0b36, name: python3
-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-[I 00:39:41.855 LabApp] Saving file at /format_opt_const.ipynb
[W 00:39:41.856 LabApp] Notebook format_opt_const.ipynb is not trusted
[I 00:40:34.502 LabApp] Saving file at /format_opt_const.ipynb
[W 00:40:34.503 LabApp] Notebook format_opt_const.ipynb is not trusted
[W 00:41:28.604 LabApp] Notebook calc_planck_opac.ipynb is not trusted
[I 00:41:29.468 LabApp] Kernel started: c8c1d48d-60a3-45bc-a937-b42a79c3d2e9, name: python3
[I 00:42:36.067 LabApp] Saving file at /format_opt_const.ipynb
[W 00:42:36.068 LabApp] Notebook format_opt_const.ipynb is not trusted
[I 01:05:28.584 LabApp] Saving file at /calc_planck_opac.ipynb
[W 01:05:28.585 LabApp] Notebook calc_planck_opac.ipynb is not trusted
[I 01:07:30.029 LabApp] Saving file at /calc_planck_opac.ipynb
[W 01:07:30.030 LabApp] Notebook calc_planck_opac.ipynb is not trusted
[I 01:07:45.226 LabApp] Kernel restarted: c8c1d48d-60a3-45bc-a937-b42a79c3d2e9
[I 01:09:33.770 LabApp] Saving file at /calc_planck_opac.ipynb
[W 01:09:33.771 LabApp] Notebook calc_planck_opac.ipynb is not trusted
[I 01:27:05.132 LabApp] Saving file at /calc_planck_opac.ipynb
[W 01:27:05.132 LabApp] Notebook calc_planck_opac.ipynb is not trusted
[I 01:29:57.577 LabApp] Starting buffering for c8c1d48d-60a3-45bc-a937-b42a79c3d2e9:8a414e34-7977-4f08-aabd-31d8ddada5b7
[I 01:29:57.578 LabApp] Starting buffering for e16d7323-78e0-482f-b65a-81c6d2ed0b36:799cd5d6-d9ab-4046-a2c8-8ba514b5cf50
[I 01:29:58.295 LabApp] Restoring connection for c8c1d48d-60a3-45bc-a937-b42a79c3d2e9:8a414e34-7977-4f08-aabd-31d8ddada5b7
[W 01:31:28.153 LabApp] WebSocket ping timeout after 90001 ms.
[W 01:31:28.227 LabApp] WebSocket ping timeout after 90001 ms.
[W 01:31:28.295 LabApp] WebSocket ping timeout after 90000 ms.
[I 01:31:33.228 LabApp] Starting buffering for e16d7323-78e0-482f-b65a-81c6d2ed0b36:799cd5d6-d9ab-4046-a2c8-8ba514b5cf50
[I 01:31:33.297 LabApp] Starting buffering for c8c1d48d-60a3-45bc-a937-b42a79c3d2e9:8a414e34-7977-4f08-aabd-31d8ddada5b7
[IPKernelApp] WARNING | Parent appears to have exited, shutting down.
[IPKernelApp] WARNING | Parent appears to have exited, shutting down.
